name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          npm run build
          ls -la dist/

      - name: Create deployment package
        run: |
          # Create clean deployment with built files and production dependencies
          mkdir deploy
          cp -r dist/* deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cd deploy
          # Install only production dependencies
          npm ci --omit=dev
          # Create a simple package.json for Azure startup
          cat > package.json << 'EOF'
          {
            "name": "smeaton-healthcare-platform",
            "version": "1.0.0",
            "type": "module",
            "scripts": {
              "start": "node index.js"
            },
            "engines": {
              "node": "20.x"
            }
          }
          EOF
          # Package everything
          zip -r ../release.zip *

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'smeaton-healthcare'  # This will be auto-updated by Azure
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          startup-command: 'npm start'