name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          npm run build
          ls -la dist/

      - name: Create deployment package
        run: |
          # Create deployment directory with correct structure
          mkdir deploy
          
          # Copy the server bundle (this is your Node.js app)
          cp dist/index.js deploy/
          
          # Copy the static assets (React frontend)  
          cp -r dist/public deploy/public
          
          # Copy real package.json and package-lock.json for full dependencies
          cp package.json deploy/
          cp package-lock.json deploy/
          
          # Install production dependencies in deploy directory
          cd deploy
          npm ci --omit=dev
          
          # Update package.json to use correct start script
          node -e "
            const pkg = JSON.parse(require('fs').readFileSync('package.json', 'utf8'));
            pkg.scripts = { start: 'node index.js' };
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
          
          # Package everything for Azure
          zip -r ../release.zip *

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'smeatonwebsite'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .