name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          npm run build
          ls -la dist/

      - name: Create deployment package
        run: |
          # Create deployment directory with correct structure
          mkdir deploy
          
          # Copy the server bundle (this is your Node.js app)
          cp dist/index.js deploy/
          
          # Copy the static assets (React frontend)  
          cp -r dist/public deploy/public
          
          # Copy real package.json and package-lock.json for full dependencies
          cp package.json deploy/
          cp package-lock.json deploy/
          
          # Install production dependencies in deploy directory
          cd deploy
          npm ci --omit=dev
          
          # Update package.json for Azure deployment
          node -e "
            const pkg = JSON.parse(require('fs').readFileSync('package.json', 'utf8'));
            pkg.scripts = { 
              start: 'NODE_ENV=production node index.js'
            };
            pkg.main = 'index.js';
            pkg.type = 'module';
            pkg.engines = { node: '>=20.0.0' };
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
          
          # Create a web.config for IIS on Azure
          cat > web.config << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <webSocket enabled="false" />
              <handlers>
                <add name="iisnode" path="index.js" verb="*" modules="iisnode"/>
              </handlers>
              <rewrite>
                <rules>
                  <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
                    <match url="^index.js\/debug[\/]?" />
                  </rule>
                  <rule name="StaticContent">
                    <action type="Rewrite" url="public{REQUEST_URI}"/>
                  </rule>
                  <rule name="DynamicContent">
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
                    </conditions>
                    <action type="Rewrite" url="index.js"/>
                  </rule>
                </rules>
              </rewrite>
              <security>
                <requestFiltering>
                  <hiddenSegments>
                    <add segment="node_modules"/>
                  </hiddenSegments>
                </requestFiltering>
              </security>
              <iisnode node_env="production" nodeProcessCommandLine="node" />
            </system.webServer>
          </configuration>
          EOF
          
          # Package everything for Azure
          zip -r ../release.zip *

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'smeatonwebsite'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .